In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import statistics as st
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [2]:
x = df.drop('target', axis = 1)
y = df['target']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

model1 = DecisionTreeClassifier()
model2 = KNeighborsClassifier()
model3= LogisticRegression()
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)
pred1=model1.predict(x_test)
pred2=model2.predict(x_test)
pred3=model3.predict(x_test)
final_pred = np.array([])
for i in range(0,len(x_test)):
    final_pred = np.append(final_pred, st.mode([pred1[i], pred2[i], pred3[i]]))
print(final_pred)

[0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0.
 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1.
 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]

In [3]:
print("Accuracy DT:", accuracy_score(y_test, pred1))
print("Accuracy KNN:", accuracy_score(y_test, pred2))
print("Accuracy LR:", accuracy_score(y_test, pred3))
print("Accuracy Ensamble Max voting:", accuracy_score(y_test, final_pred))
print("Roll Num: CB.SC.I5DAS21049")
print("Name: Pratiksha Cauvery K P")

Accuracy DT: 0.7868852459016393
Accuracy KNN: 0.639344262295082
Accuracy LR: 0.8524590163934426
Accuracy Ensamble Max voting: 0.8524590163934426
Roll Num: CB.SC.I5DAS21049
Name: Pratiksha Cauvery K P

# Voting Classifier

In [4]:
from sklearn.ensemble import VotingClassifier
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
model1 = DecisionTreeClassifier()
model2 = KNeighborsClassifier()
model3= LogisticRegression()
model = VotingClassifier(estimators=[('dt', model1), ('knn', model2), ('lr', model3)])
model.fit(x_train,y_train)
y_predict=model.predict(x_test)
print("Accuracy Ensamble Max voting:", accuracy_score(y_test, y_predict))
print("Roll Num: CB.SC.I5DAS21049")
print("Name: Pratiksha Cauvery K P")

Accuracy Ensamble Max voting: 0.819672131147541
Roll Num: CB.SC.I5DAS21049
Name: Pratiksha Cauvery K P