In [8]:
import pandas as pd
from sklearn import preprocessing, utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [9]:
df = pd.read_csv('heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [10]:
X = df.drop('target', axis=1)
Y = df['target']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8)
print("Shape of X: ",X.shape)
print("Shape of Y",Y.shape)
print("Shape of X_train",X_train.shape)
print("Shape of X_test",X_test.shape)
print("Shape of Y_train",Y_train.shape)
print("Shape of Y_test",Y_test.shape)

Shape of X:  (303, 13)
Shape of Y (303,)
Shape of X_train (242, 13)
Shape of X_test (61, 13)
Shape of Y_train (242,)
Shape of Y_test (61,)

# Gaussian Naive Bayes

In [11]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, Y_train)
gnb_pred  = gnb.predict(X_test)
print('Predicted Value:', gnb_pred)
print('Actual Value:', Y_test)
print("Accuracy Score: ", accuracy_score(Y_test,gnb_pred))
print("Roll Num: CB.SC.I5DAS21049")
print("Name: Pratiksha Cauvery K P")

Predicted Value: [1 0 1 0 1 1 1 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1 1
 0 1 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0]
Actual Value: 130    1
280    0
123    1
66     1
75     1
      ..
151    1
121    1
71     1
264    0
110    1
Name: target, Length: 61, dtype: int64
Accuracy Score:  0.819672131147541
Roll Num: CB.SC.I5DAS21049
Name: Pratiksha Cauvery K P

# Support Vector Machines

In [12]:
from sklearn.svm import SVC

svm = SVC(kernel = 'linear')
svm.fit(X_train, Y_train)
svm_pred = svm.predict(X_test)
print('Predicted Value:', svm_pred)
print('Actual Value:', Y_test)
print("Accuracy Score: ", accuracy_score(Y_test,svm_pred))
print("Roll Num: CB.SC.I5DAS21049")
print("Name: Pratiksha Cauvery K P")

Predicted Value: [1 0 1 1 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 1 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1
 0 1 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 0 1]
Actual Value: 130    1
280    0
123    1
66     1
75     1
      ..
151    1
121    1
71     1
264    0
110    1
Name: target, Length: 61, dtype: int64
Accuracy Score:  0.8524590163934426
Roll Num: CB.SC.I5DAS21049
Name: Pratiksha Cauvery K P

# Decision Tree Classifier

In [13]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train,Y_train)
dtc_pred = dtc.predict(X_test)
print('Predicted Value:', dtc_pred)
print('Actual Value:', Y_test)
print("Accuracy Score: ", accuracy_score(Y_test,dtc_pred))
print("Roll Num: CB.SC.I5DAS21049")
print("Name: Pratiksha Cauvery K P")

Predicted Value: [1 0 1 0 1 1 0 0 1 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 1 0 0 1 1
 0 1 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 0]
Actual Value: 130    1
280    0
123    1
66     1
75     1
      ..
151    1
121    1
71     1
264    0
110    1
Name: target, Length: 61, dtype: int64
Accuracy Score:  0.7213114754098361
Roll Num: CB.SC.I5DAS21049
Name: Pratiksha Cauvery K P

# K Nearest Neighbors

In [14]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
knn_pred = knn.predict(X_test)
print('Predicted Value:', knn_pred)
print('Actual Value:', Y_test)
print("Accuracy Score: ", accuracy_score(Y_test, knn_pred))
print("Roll Num: CB.SC.I5DAS21049")
print("Name: Pratiksha Cauvery K P")

Predicted Value: [1 0 1 1 1 1 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 1 1
 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 0 0 0 1 1 1 0]
Actual Value: 130    1
280    0
123    1
66     1
75     1
      ..
151    1
121    1
71     1
264    0
110    1
Name: target, Length: 61, dtype: int64
Accuracy Score:  0.6229508196721312
Roll Num: CB.SC.I5DAS21049
Name: Pratiksha Cauvery K P